ASPMainProject/Controllers/AdController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ASPMainProject.Models;
using ASPMainProject.Services;

namespace ASPMainProject.Controllers
{
    public class AdController : Controller
    {
        private readonly AdService _adService = new AdService();
        private readonly KeyWordsService _keyWordsService = new KeyWordsService();
        //
        // GET: /Ad/
        public ActionResult Index(Guid? employerId = null)
        {
            var model = new AdsWithKeyWords();

            //we dont use filter, we return all ads
            if (employerId == null)
                model.Ads = _adService.GetAllAds();
            else
                model.Ads = _adService.GetAdsByAuthorId(employerId ?? Guid.Empty);

            model.KeyWordPreviews = _keyWordsService.GetAllKeyWords();

            return View(model);
        }
        
        [HttpPost]
        public ActionResult Index(AdsWithKeyWords model)
        {
            if (model == null || model.KeyWordPreviews == null)
            {
                return RedirectToAction("Index");
            }

            var res = model.KeyWordPreviews.Where(f => f.Selected).ToList();
            if (res.Count() == 0)
                return RedirectToAction("Index");

            model.Ads = _adService.GetFilteredAds
                (res.Select(p => p.Id));
            return View(model);
        }
        public ActionResult Details(Guid adId)
        {
            //var model = new Ad() { Location = "Lviv" };
            var model = _adService.GetAdById(adId);
            return View(model);
        }


        public ActionResult DetailsForm(Guid adId)
        {
            //var model = new Ad() { Location = "Lviv" };
            var model = _adService.GetAdById(adId);

            var allKeyWords = _keyWordsService.GetAllKeyWords();
            foreach (var item in allKeyWords)
            {
                if (model.KeyWords.ContainsKey(item.Id))
                    item.Selected = true;
            }

            model.KeyWordPreviews = (allKeyWords);

            return View(model);
        }


        [HttpPost]
        public ActionResult DetailsForm(Ad ad)
        {
            if (ad != null)
            {
                if (ad.KeyWordPreviews != null)
                    ad.KeyWords = ad.KeyWordPreviews.Where(f => f.Selected)
                        .Select(x => x.Id)
                        .ToDictionary(item => item, item => "");
            }
            var result = _adService.Update(ad);
            return RedirectToAction("Details", new { adId = ad.Id });
        }
	
        public ActionResult AddNewAd(/*Guid authorId*/)
        {
            var userService = new UserService();

            var es = new EmployerService();
            var currEmplId = es.GetEmployerIdByUserId
                (userService.GetUserIdByUserName(User.Identity.Name));

            if (currEmplId == Guid.Empty)
                return Content("You should log in or register at first");

            var res = _adService.AddNewAd(new Ad() { AuthorId = currEmplId });
            return RedirectToAction("DetailsForm", new { adId = res
                 });
        }
    }
}

ASPMainProject/Controllers/CandidateController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ASPMainProject.Models;
using ASPMainProject.Services;

namespace ASPMainProject.Controllers
{
    public class CandidateController : Controller
    {
        private readonly CandidateService _candidateService = new CandidateService();
        private readonly KeyWordsService _keyWordsService = new KeyWordsService();
        //
        // GET: /Candidate/
        public ActionResult Index(/*List<CandidatePreview> candidatePreviews = null, List<KeyWordPreview> filterKeyWordPreviews = null*/)
        {       
            var model = new CandidatePreviewsWithKeyWordPreviews();

            //we dont use filter, we return all cands
            model.CandidatePreviews = (_candidateService.GetAllCandidates());
            model.KeyWordPreviews = (_keyWordsService.GetAllKeyWords());
            
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(CandidatePreviewsWithKeyWordPreviews model)
        {
            if (model == null || model.KeyWordPreviews == null)
            {
                return RedirectToAction("Index");
            }

            var res = model.KeyWordPreviews.Where(f => f.Selected).ToList();
            if (res.Count() == 0)
                return RedirectToAction("Index");

            model.CandidatePreviews = _candidateService.GetFilteredCandidatePreviews
                (res.Select(p => p.Id));
            return View(model);
        }

        public ActionResult Details(Guid candidateId)
        {
            //cand details
            var model = _candidateService.GetCandidateById(candidateId);
            return View(model);
        }


        public ActionResult DetailsForm(Guid candidateId)
        {
            //edit cand details
            var model = _candidateService.GetCandidateById(candidateId);

            var allKeyWords = _keyWordsService.GetAllKeyWords();
            foreach(var item in allKeyWords)
            {
                if (model.KeyWords.ContainsKey(item.Id))
                    item.Selected = true;
            }

            model.KeyWordPreviews = (allKeyWords);
            return View(model);
        }

        [HttpPost]
        public ActionResult DetailsForm(Candidate candidate)
        {
            candidate.KeyWords = candidate.KeyWordPreviews.Where(f => f.Selected).Select(x => x.Id).ToDictionary(item => item, item => "");
            var result = _candidateService.Update(candidate);
            return RedirectToAction("Details", new { candidateId = candidate.Id });
        }
	}
}

ASPMainProject/Controllers/EmployerController.cs
using System;
using System.Web.Mvc;
using ASPMainProject.Services;
using ASPMainProject.Models;

namespace ASPMainProject.Controllers
{
    public class EmployerController : Controller
    {
        private readonly EmployerService _employerService = new EmployerService();
        //
        // GET: /Employer/
        public ActionResult Index()
        {
            //var model = new List<Employer>() { new Employer() { Id = new Guid(), FullName = "Some Man", ApprovingState = ApprovingState.Approved }, new Employer() { Id = new Guid(), FullName = "Another Man", ApprovingState = ApprovingState.Approved } };
            var model = _employerService.GetAllEmployers();
            return View(model);
        }

        public ActionResult Details(Guid id)
        {
            //empl details
            //var model = new Employer() {Id = id, Company = "Box1" };
            var model = _employerService.GetEmployerById(id);
            return View(model);
        }


        public ActionResult DetailsForm(Guid id)
        {
            //edit empl details
            //var model = new Employer() {Id = id, Company = "COMPANY111111" };
            var model = _employerService.GetEmployerById(id);
            return View(model);
        }


        [HttpPost]
        public ActionResult DetailsForm(Employer employer)
        {
            //edit empl details
            //var model = new Employer() { Company = "COMPANY111111" };
            var result = _employerService.Update(employer);
            return RedirectToAction("Details", new { id = employer.Id });
        }
	}
}

ASPMainProject/Controllers/MessageController.cs
using System;
using System.Web.Mvc;
using System.Web.WebPages;
using ASPMainProject.Services;

namespace ASPMainProject.Controllers
{
    public class MessageController : Controller
    {
        readonly MessageService _messageService = new MessageService();
        readonly UserService _userservice = new UserService();
        //
        // GET: /Message/
        public ActionResult Index()
        {
            Guid currentUserId = _userservice.GetUserIdByUserName(User.Identity.Name); //new Guid("57013564-eb60-49b7-8155-345eac12ff93");
            var model = _messageService.GetChatsPreviewByUserId(currentUserId);
            return View(model);
        }

        //show one chat
        public ActionResult Chat(Guid chatId)
        {
            Guid currentUserId = _userservice.GetUserIdByUserName(User.Identity.Name);//new Guid("57013564-eb60-49b7-8155-345eac12ff93");
            var model = _messageService.GetChatByChatId(chatId, currentUserId);            
            model.CurrentUserId = currentUserId;

            //If we got so far, we have read messages in current chat
            _messageService.MarkAllMessagesAsReadInChat(chatId, currentUserId);

            return View(model);
        }

        [HttpPost]
        public ActionResult SendMessageTo(Guid receiverId, string messageText)
        {  
            Guid currentUserId = _userservice.GetUserIdByUserName(User.Identity.Name);//new Guid("57013564-eb60-49b7-8155-345eac12ff93");
            
            if (currentUserId == Guid.Empty || receiverId == Guid.Empty)
                return Content("You should login or register first. \n (Or your interlocutor's account doesn't exist)");

            Guid chatId = _messageService.SendMessageTo(receiverId, currentUserId, messageText);
            return RedirectToAction("Chat", new { chatId = chatId });
        }
	}
}

ASPMainProject/Views/Shared/CandidatesAdsHistorgam.cshtml
@model System.Collections.ArrayList

@*<script type="text/javascript">
    $(document).ready(drawChart(@Html.Raw(Json.Encode(@Model))));
</script>*@
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', { 'packages': ['bar'] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data =
            google.visualization.arrayToDataTable(@Html.Raw(Json.Encode(@Model))
                //[
              //  ['KeyWord', 'Cand', 'Empl'],
              //  ['c#', 1000, 400],
              //  ['php', 1170, 460],
              //  ['rr', 660, 1120],
              //  ['5', 1030, 540]
              //]
            );

        var options = {
            chart: {
                title: 'Candidates to Adverticemenys correlation',
                subtitle: 'Amount of candidates, amount of vacancies by keyword'
            }
        };

        var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

        chart.draw(data, options);
    }
</script>

    <body>
        <div style="border-color:red">
            <div id="columnchart_material" style="width: auto; height: auto; padding:1px;"></div>
        </div>
    </body>

ASPMainProject/Views/Shared/_Layout.cshtml
@using ASPMainProject.Services;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")  @*I neen this to use jquery*@

    <asp:ScriptManager ID="ScriptManager1" runat="server" EnablePageMethods="true">
    </asp:ScriptManager>

    <script type="text/javascript">
        $(document).ready(function GetNewMessageCountByUserName() {
            var i = @MessageService.GetNewMessageCountByUserName(User.Identity.Name).ToString();
            if (i=='0')
                document.getElementById('NewMessageCount').innerHTML = '';
            else
                document.getElementById('NewMessageCount').innerHTML = i;
        });
    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("JobSeeker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div><div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (!Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    }
                    @if (Request.IsAuthenticated)
                    {
                        <li>
                            <a href="@Url.Action("Index", "Message")">
                                Messages
                                <span id="NewMessageCount" class="badge"></span>
                            </a>
                        </li>
                    }

                    <li>@Html.ActionLink("Candidates", "Index", "Candidate")</li>
                    <li>@Html.ActionLink("Employers", "Index", "Employer")</li>
                    <li>@Html.ActionLink("Adverticements", "Index", "Ad")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - JobSeeker</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>